// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtNMfP_K8vq1PTaD-Nd7i_KeKacLjLFe8',
    appId: '1:270858510321:web:fd8135931faff951d12e50',
    messagingSenderId: '270858510321',
    projectId: 'mawar-care',
    authDomain: 'mawar-care.firebaseapp.com',
    storageBucket: 'mawar-care.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUJ-lBXVZp3fTg3DV1ZzUTRARpBqv5d6Y',
    appId: '1:270858510321:android:eaac8d045f5a4e89d12e50',
    messagingSenderId: '270858510321',
    projectId: 'mawar-care',
    storageBucket: 'mawar-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXW2jCgiw9F8zPdZ6keHPukJZG7CE1K2o',
    appId: '1:270858510321:ios:b34583ec023ff473d12e50',
    messagingSenderId: '270858510321',
    projectId: 'mawar-care',
    storageBucket: 'mawar-care.appspot.com',
    iosBundleId: 'com.example.mawarCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXW2jCgiw9F8zPdZ6keHPukJZG7CE1K2o',
    appId: '1:270858510321:ios:494128291cfc8cf2d12e50',
    messagingSenderId: '270858510321',
    projectId: 'mawar-care',
    storageBucket: 'mawar-care.appspot.com',
    iosBundleId: 'com.example.mawarCare.RunnerTests',
  );
}
